[Unit]
After=epikur-preview-db.service
Wants=epikur-preview-db.service

[Service]
Environment=NODE_OPTIONS=--max-old-space-size=1024
ExecStart=
ExecStart=/usr/bin/npm run dev -- --hostname 127.0.0.1 --port 3010
MemoryHigh=1100M
MemoryMax=1300M
